default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: boilerplate_app_development

test:
  <<: *default
  database: boilerplate_app_test

production:
  <<: *default
  database: boilerplate_app_production
  username: rails_boilerplate_postgresql
  password: <%= ENV['RAILS_BOILERPLATE_POSTGRESQL_DATABASE_PASSWORD'] %>
