default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRESQL_DATABASE_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production
  username: <%= ENV['POSTGRESQL_DATABASE_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_DATABASE_PASSWORD'] %>
